<?php

// This file is fully generated by AI; use only for testing purposes.
// Model: Claude Haiku 4.5
// Used prompt: Create a PHP code file with multiple classes and keep it
//              small and simple.
// Generation date: 15-04-2026

class Calculator {
    public function add($a, $b) {
        if ($a == null || $b == null) return 0;
        return $a + $b;
    }

    public function multiply($a, $b) {
        $result = 0;
        for ($i = 0; $i < $a; $i++) $result += $b;
        return $result;
    }
}

class Logger {
    public function log($message) {
        echo "[LOG] " . $message . "\n";
    }
}

$calc = new Calculator();
$logger = new Logger();

$sum = $calc->add(5, 3);
$product = $calc->multiply(4, 2);

$logger->log("Sum: " . $sum);
$logger->log("Product: " . $product);

?>
