from logging import getLogger
from pathlib import Path
from subprocess import PIPE, TimeoutExpired, run as subprocess_run
from tempfile import TemporaryDirectory
from typing import Dict, List, Optional, Tuple, TypedDict
from src.pipeline.worker_context import get_worker_index
from src.settings import settings
from glob import glob
from xml.etree import ElementTree

logger = getLogger(__name__)


class EBTestFailure(TypedDict):
    suite: str
    test: str
    message: str


def run_eb_tests(output_dir: str, worker_index: int) -> Tuple[int, str]:
    """
    Runs the EB test suite using the provided output directory. The test
    results are expected to be saved in JUnit XML format in the specified
    output directory.

    Args:
        output_dir (str): The directory where the test results should be saved.
        worker_index (int): Index of the isolated EngineBlock environment.

    Returns:
        Tuple[int, str]: The return code of the test execution, and its
            captured stderr.
    """

    _runner = Path(__file__).parent / 'run_eb_tests.sh'

    try:
        cmd = ['bash', str(_runner), output_dir, str(worker_index)]
        result = subprocess_run(
            cmd,
            timeout=settings.correctness_check_timeout,
            stderr=PIPE,
            text=True,
        )
    except TimeoutExpired:
        logger.error(
            'EB tests timed out after '
            f'{settings.correctness_check_timeout} seconds.'
        )
        return 1, ''
    return result.returncode, result.stderr or ''


def parse_and_format_eb_test_results(output_dir: str) -> str:
    """
    Returns a formatted string of all EB test failures or errors found in the
    JUnit XML test results located in the specified output directory.
    The format is as follows:
    ```
    SUITE:  <suite_name>
    TEST:   <test_name>
    <failure message lines>
    ---
    ```
    """

    def parse_eb_test_results(output_dir: str) -> List[EBTestFailure]:
        """
        Parses the JUnit XML test results generated by the EB test suite and
        extracts any test failures or errors.

        Args:
            output_dir (str): The directory where the JUnit XML test results are
                located.

        Returns:
            List[EBTestFailure]: A list of test failures or errors.
        """

        failures: List[EBTestFailure] = []
        for xml_path in sorted(glob(f'{output_dir}/phpunit-*.xml')):
            suite_name = Path(xml_path).stem.removeprefix('phpunit-')
            try:
                tree = ElementTree.parse(xml_path)
            except ElementTree.ParseError as _error:
                logger.warning(
                    'Could not parse JUnit results %s: %s', xml_path, _error
                )
                continue
            for testcase in tree.iter('testcase'):
                for child in testcase:
                    if child.tag not in ('failure', 'error'):
                        continue

                    classname = testcase.get('classname', '')
                    name = testcase.get('name', '')

                    failures.append(
                        EBTestFailure(
                            suite=suite_name,
                            test=f'{classname}.{name}' if classname else name,
                            message=(child.text or '').strip(),
                        )
                    )
        return failures

    def format_failures(failures: List[EBTestFailure]) -> str:
        """
        Formats parsed EB test failures into a singular string:
        ```
        SUITE:  eb4
        TEST:   SomeTest::testFoo
        <failure message lines>
        ---
        ```

        Failures sharing an identical message are collapsed into one block
        listing every affected test, and only the first
        `settings.max_reported_test_failures` distinct messages are included,
        to keep the output within the LLM's context window.

        Args:
            failures (List[EBTestFailure]): A list of EB test failures.

        Returns:
            str: The formatted string containing all test failures.
        """

        tests_by_message: Dict[str, List[str]] = {}
        message_order: List[str] = []
        suite_by_message: Dict[str, str] = {}
        for failure in failures:
            message = failure['message']
            if message not in tests_by_message:
                tests_by_message[message] = []
                message_order.append(message)
                suite_by_message[message] = failure['suite']
            tests_by_message[message].append(failure['test'])

        total_messages = len(message_order)
        shown_messages = message_order[: settings.max_reported_test_failures]

        blocks = []
        for message in shown_messages:
            tests = tests_by_message[message]
            lines = [f'SUITE:  {suite_by_message[message]}']
            lines.extend(f'TEST:   {test}' for test in tests)
            if message:
                lines.append(message)
            lines.append('---')
            blocks.append('\n'.join(lines))

        omitted = total_messages - len(shown_messages)
        if omitted > 0:
            blocks.append(
                f'... {omitted} more distinct failure(s) omitted for '
                'brevity ...'
            )

        return '\n'.join(blocks) + '\n' if blocks else ''

    return format_failures(parse_eb_test_results(output_dir))


def correctness_check_eb(
    worker_index: Optional[int] = None,
) -> Tuple[bool, str]:
    """
    Runs the EB test suite against an isolated EngineBlock environment.

    Args:
        worker_index (Optional[int]): Which isolated environment to run against.
            When None (the standard, synchronous pipeline path) it is resolved
            from the worker index bound to the calling thread. Callers that may
            execute on a different thread than the one that claimed the worker
            must pass it explicitly.

    Returns:
        Tuple[bool, str]: A tuple where the first element is a boolean
            indicating whether the tests passed, and the second element is a
            string containing the formatted output of any test failures or
            errors.
    """

    if worker_index is None:
        worker_index = get_worker_index()

    with TemporaryDirectory() as output_dir:
        runner_return_code, runner_stderr = run_eb_tests(
            output_dir, worker_index
        )

        # Try to parse anything anyway even if the runner failed,
        # to get as much information as possible.
        failures = parse_and_format_eb_test_results(output_dir)
        if runner_return_code == 0:
            return (True, failures)

        # A stage before any PHPUnit suite runs (cache:clear, schema
        # reset, ...) can fail, leaving no JUnit XML behind and thus no
        # parsed failures. Without this, the LLM would get an empty test
        # output and no signal about what actually broke.
        if not failures:
            return (
                False,
                runner_stderr or 'The correctness check failed with no output.',
            )
        return (False, failures)
