from logging import getLogger
from pathlib import Path
from subprocess import TimeoutExpired, run as subprocess_run
from tempfile import TemporaryDirectory
from typing import List, Tuple, TypedDict
from src.settings import settings
from glob import glob
from xml.etree import ElementTree

logger = getLogger(__name__)


class EBTestFailure(TypedDict):
    suite: str
    test: str
    message: str


def run_eb_tests(output_dir: str) -> int:
    """
    Runs the EB test suite using the provided output directory. The test
    results are expected to be saved in JUnit XML format in the specified
    output directory.

    Args:
        output_dir (str): The directory where the test results should be saved.

    Returns:
        int: The return code of the test execution.
    """

    _runner = Path(__file__).parent / 'run_eb_tests.sh'

    try:
        cmd = ['bash', str(_runner), output_dir]
        result = subprocess_run(cmd, timeout=settings.correctness_check_timeout)
    except TimeoutExpired:
        logger.error(
            'EB tests timed out after '
            f'{settings.correctness_check_timeout} seconds.'
        )
        return 1
    return result.returncode


def parse_and_format_eb_test_results(output_dir: str) -> str:
    """
    Returns a formatted string of all EB test failures or errors found in the
    JUnit XML test results located in the specified output directory.
    The format is as follows:
    ```
    SUITE:  <suite_name>
    TEST:   <test_name>
    <failure message lines>
    ---
    ```
    """

    def parse_eb_test_results(output_dir: str) -> List[EBTestFailure]:
        """
        Parses the JUnit XML test results generated by the EB test suite and
        extracts any test failures or errors.

        Args:
            output_dir (str): The directory where the JUnit XML test results are
                located.

        Returns:
            List[EBTestFailure]: A list of test failures or errors.
        """

        failures: List[EBTestFailure] = []
        for xml_path in sorted(glob(f'{output_dir}/phpunit-*.xml')):
            suite_name = Path(xml_path).stem.removeprefix('phpunit-')
            tree = ElementTree.parse(xml_path)
            for testcase in tree.iter('testcase'):
                for child in testcase:
                    if child.tag not in ('failure', 'error'):
                        continue
                    failures.append(
                        EBTestFailure(
                            suite=suite_name,
                            test=f'{testcase.get("classname", "")}.{testcase.get("name", "")}',
                            message=(child.text or '').strip(),
                        )
                    )
        return failures

    def format_failures(failures: List[EBTestFailure]) -> str:
        """
        Formats parsed EB test failures into a singular string:
        ```
        SUITE:  eb4
        TEST:   SomeTest::testFoo
        <failure message lines>
        ---
        ```

        Args:
            failures (List[EBTestFailure]): A list of EB test failures.

        Returns:
            str: The formatted string containing all test failures.
        """

        blocks = []
        for failure in failures:
            lines = [
                f'SUITE:  {failure["suite"]}',
                f'TEST:   {failure["test"]}',
            ]
            if failure['message']:
                lines.append(failure['message'])
            lines.append('---')
            blocks.append('\n'.join(lines))
        return '\n'.join(blocks)

    return format_failures(parse_eb_test_results(output_dir))


def correctness_check_eb() -> Tuple[bool, str]:
    """
    Runs the EB test suite.

    Returns:
        Tuple[bool, str]: A tuple where the first element is a boolean
            indicating whether the tests passed, and the second element is a
            string containing the formatted output of any test failures or
            errors.
    """

    with TemporaryDirectory() as output_dir:
        runner_return_code = run_eb_tests(output_dir)
        # Try to parse anything anyway even if the runner failed,
        # to get as much information as possible.
        failures = parse_and_format_eb_test_results(output_dir)
        return (runner_return_code == 0, failures)
